// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/:serviceId": {
    params: {
      "serviceId": string;
    };
  };
  "/pricing": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
  "/our-clients": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/faqs": {
    params: {};
  };
  "/seo": {
    params: {};
  };
  "/kpi": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/services" | "/services/:serviceId" | "/pricing" | "/blog" | "/blog/:slug" | "/contact" | "/contacto" | "/our-clients" | "/about" | "/faqs" | "/seo" | "/kpi" | "/*";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  } | {
    id: "about";
    page: "/about";
  };
  "routes/services.jsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/service-detail.jsx": {
    id: "routes/service-detail";
    page: "/services/:serviceId";
  };
  "routes/pricing.jsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/blog.jsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blog-post.jsx": {
    id: "routes/blog-post";
    page: "/blog/:slug";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  } | {
    id: "contact-es";
    page: "/contacto";
  };
  "routes/our-clients.jsx": {
    id: "routes/our-clients";
    page: "/our-clients";
  };
  "routes/faqs.jsx": {
    id: "routes/faqs";
    page: "/faqs";
  };
  "routes/seo.jsx": {
    id: "routes/seo";
    page: "/seo";
  };
  "routes/kpi.jsx": {
    id: "routes/kpi";
    page: "/kpi";
  };
  "routes/catch-all.jsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/services": typeof import("./app/routes/services.jsx");
  "routes/service-detail": typeof import("./app/routes/service-detail.jsx");
  "routes/pricing": typeof import("./app/routes/pricing.jsx");
  "routes/blog": typeof import("./app/routes/blog.jsx");
  "routes/blog-post": typeof import("./app/routes/blog-post.jsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "contact-es": typeof import("./app/routes/contact.jsx");
  "routes/our-clients": typeof import("./app/routes/our-clients.jsx");
  "about": typeof import("./app/routes/home.jsx");
  "routes/faqs": typeof import("./app/routes/faqs.jsx");
  "routes/seo": typeof import("./app/routes/seo.jsx");
  "routes/kpi": typeof import("./app/routes/kpi.jsx");
  "routes/catch-all": typeof import("./app/routes/catch-all.jsx");
};